bolbol/bolbol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bolbol/web/urls.py
from django.urls import path
from .views import *


app_name = "web"

urlpatterns = [
    path(
        "",
        HomeView.as_view(),
        name="home"
    ),
    path(
        "neqliyyat/",
        CategoryTransportView.as_view(),
        name="category-transport"
    ),
    path(
        "dashinmaz-emlak/",
        CategoryEstateView.as_view(),
        name="category-estate"
    ),
    path(
        "transport-filters/",
        TransportFiltersView.as_view(),
        name="transport-filters"
    ),
    path(
        "elektronika/",
        CategoryElectronicsView.as_view(),
        name="category-electronics"
    ),
    path(
        "ushaq-alemi/",
        CategoryBabyWorldView.as_view(),
        name="category-baby_world"
    ),
    path(
        "geyim/",
        CategoryClothesView.as_view(),
        name="category-clothes"
    ),
    path(
        "kosmetika-ve-saglamliq/",
        CategoryCosmeticsView.as_view(),
        name="category-cosmetic"
    ),
    path(
        "kosmetika-ve-saglamliq/",
        CategoryCosmeticsView.as_view(),
        name="category-cosmetics"
    ),
    path(
        "ish-elanlari/",
        CategoryJobVacanciesView.as_view(),
        name="category-job_vacancies"
    ),
    path(
        "ev-ve-bag/",
        CategoryHomeGardenView.as_view(),
        name="category-home_garden"
    ),
    path(
        "erzaq/",
        CategoryMealView.as_view(),
        name="category-meal"
    ),
    path(
        "heyvan-ve-bitki/",
        CategoryAnimalsPlantsView.as_view(),
        name="category-animals_plants"
    ),
    path(
        "idman-musiqi-hobbi/",
        CategorySportMusicHobbyView.as_view(),
        name="category-sport_music_hobby"
    ),
    path(
        "diger/",
        CategoryOthersView.as_view(),
        name="category-others"
    ),
    path(
        "xidmetler/",
        CategoryServicesView.as_view(),
        name="category-services"
    ),
    path(
        "elektronika/telefonlar/",
        SubcategoryTelephonesView.as_view(),
        name="subcategory-telephones"
    )
]

bolbol/web/models.py
from django.db import models

# Create your models here.

bolbol/web/views/categories.py
from django.views import generic


class CategoryTransportView(generic.TemplateView):
    template_name = "categories/transport.html"


class TransportFiltersView(generic.TemplateView):
    template_name = "categories/transport_filters.html"


class CategoryEstateView(generic.TemplateView):
    template_name = "categories/estate.html"


class CategoryElectronicsView(generic.TemplateView):
    template_name = "categories/electronics.html"


class CategoryBabyWorldView(generic.TemplateView):
    template_name = "categories/baby_world.html"


class CategoryClothesView(generic.TemplateView):
    template_name = "categories/clothes.html"


class CategoryCosmeticsView(generic.TemplateView):
    template_name = "categories/cosmetics.html"


class CategoryJobVacanciesView(generic.TemplateView):
    template_name = "categories/job_vacancies.html"


class CategoryHomeGardenView(generic.TemplateView):
    template_name = "categories/home_garden.html"


class CategoryMealView(generic.TemplateView):
    template_name = "categories/meal.html"


class CategoryAnimalsPlantsView(generic.TemplateView):
    template_name = "categories/animals_plants.html"


class CategorySportMusicHobbyView(generic.TemplateView):
    template_name = "categories/sport_music_hobby.html"


class CategoryOthersView(generic.TemplateView):
    template_name = "categories/others.html"


class CategoryServicesView(generic.TemplateView):
    template_name = "categories/services.html"

bolbol/web/views/index.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "web/home.html"

bolbol/web/views/subcategories.py
from django.views.generic import TemplateView


class SubcategoryTelephonesView(TemplateView):
    template_name = "subcategories/telephones.html"

bolbol/web/templates/other/categories.html
{% load static %}

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-5 col-md-9 mx-auto">
                {% include 'partials/search_input.html' %}
            </div>
        </div>
        <div class="category">
            <div class="category__list">
                {% for category in top_categories %}
                    {% if category.name == 'Mağaza və şirkətlər' or category.pk == 23 %}
                    <a href="{% url 'web:shops-list' %}" class="category__item">
                        <img src="{% if category.icon %}{{ category.icon.url }}{% endif %}" alt="category-icon">
                        {{ category.name }}
                    </a>
                    {% else %}
                    <a href="{% url 'web:catalog-2' category_pk=category.pk child_pk=0 %}?category_id={{ category.id }}" class="category__item">
                        <img src="{% if category.icon %}{{ category.icon.url }}{% endif %}" alt="category-icon">
                        {{ category.name }}
                    </a>
                    {% endif %}
                {% endfor %}
            </div>
            <a class="btn category__btn">Bütün kateqoriyalar</a>
        </div>
    </div>
</section>

bolbol/web/templates/partials/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Bolbol</title>
    <meta name="description" content="" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <meta
      name="viewport"
      content="width=device-width, minimum-scale=1.0, maximum-scale=3.0, initial-scale=1.0"
    />
    <meta name="theme-color" content="#013F44" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'web/libs/normalize.css/normalize.css' %}"
    />

    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js' %}"></script>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'web/libs/bootstrap/bootstrap.min.css' %}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'web/libs/lightslider/lightslider.min.css' %}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'web/libs/sumogallery/sumogallery.css' %}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'web/libs/bootstrap-select/bootstrap-select.min.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'web/libs/bootstrap-datetimepicker/tempusdominus-bootstrap-4.css' %}"
    />

    <!-- <link rel="stylesheet" href="{% static 'web/css/main/main3.css' %}" /> -->
    <link rel="stylesheet" href="{% static 'web/css/main/main.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/main/main4.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'web/css/main/main3.css" /> -->
    <meta name="theme-color" content="#013F44" />

    <link
      rel="stylesheet"
      type="text/css"
      href="assets/libs/normalize.css/normalize.css"
    />

    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <link
      rel="stylesheet"
      type="text/css"
      href="assets/libs/bootstrap/bootstrap.min.css"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="assets/libs/lightslider/lightslider.min.css"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="assets/libs/sumogallery/sumogallery.css"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="assets/libs/bootstrap-select/bootstrap-select.min.css"
    />

    <link
      rel="stylesheet"
      href="assets/libs/bootstrap-datetimepicker/tempusdominus-bootstrap-4.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% include 'partials/inline_styles.html' %}
</head>

bolbol/web/templates/partials/header.html
{% load static %}
<header class="header">
    <div class="main_container">
      <div class="header__topbar" id="standardTopBar">
        <div class="contact">
          <a href="" class="contact__network facebook"></a>
          <a href="" class="contact__network instagram"></a>
          <span class="contact__tel">
              Dəstək:
              <a href="tel:">012 555 65 00 | 055 262 65 00 </a>
          </span>
          <a href="" class="contact__network whatsapp"></a>
          <a href="" class="contact__network telegram"></a>
        </div>
        <div class="d-md-flex align-items-center">
          <img src="{% static 'web/img/logout-icon.svg' %}" />
          <a href="/auth/logout/">Çıxış</a>
        </div>
      </div>
    </div>
    <div class="navbar_bg">
      <div class="main_container">
        <nav class="navbar navbar-expand-md" id="standardNavbar">
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggler"
            aria-controls="navbarToggler"
            aria-expanded="false"
            aria-label="Toggle navigation"
          ></button>
          <a class="navbar-brand" href="{% url 'web:home' %}">
            <img src="{% static 'web/img/logo.svg' %}" alt="logo" />
          </a>
          <div class="collapse navbar-collapse" id="navbarToggler">
            <div class="header__links">
              <a href="" class="header__link header__link--favorites"
                >Seçdiklərim</a
              >
              <a
                href=""
                class="header__link header__link--login"
                data-toggle="modal"
                data-target="#loginModal"
                >Şəxsi kabinet</a
              >
              <!-- <a href="" class="header__link header__link--login">Şəxsi kabinet</a> -->
              <!-- <a href="" class="header__link header__link--logout">Çıxış et</a> -->
            </div>
          </div>
          <a href="" class="btn header__btn"><span>Yeni elan</span></a>
        </nav>
      </div>
    </div>
</header>

bolbol/web/templates/partials/index.html
{% extends 'web/base.html' %}
{% load static i18n %}

{% block content %}
<main>
    <div id="meta" reset-offset='1'></div>
    {% include 'partials/categories.html' with hard_search=True %}
	
    <section class="vip-section">
        <div class="title title--left">
            <span class="center-vertical">
                <img src="{% static 'web/img/vip-large.svg' %}" alt="" class="mr-10">
                {% trans 'VIP ads' %}
            </span>
            <a class="btn btn--icon btn--transparent" href="{% url 'web:catalog-vip' %}{% include 'partials/_request_GET.html' %}">
                <img src="{% static 'web/img/chevron_lmain.svg' %}" alt="">
                {% trans 'All VIP advertisements' %}
            </a>
        </div>
        {% include 'partials/products_section.html' with type='vip' div_id='section_1' shuffled=True %}
    </section>
    {% include 'partials/horizontal_banner.html' %}
    <section class="fresh-section">
        <div class="title title--left">
            <span class="center-vertical">
                {% trans 'Fresh ads' %}
            </span>
            <a class="btn btn--icon btn--transparent" href="{% url 'web:catalog-fresh' %}{% include 'partials/_request_GET.html' %}?fresh=True">

                <img src="{% static 'web/img/chevron_lmain.svg' %}" alt="">
                {% trans 'Bütün yeni elanlar' %}
            </a>
        </div>
        {% include 'partials/products_section.html' with type='sim' div_id='section_2' shuffled=True latest=True %}
    </section>
    {% include 'partials/horizontal_banner2.html' %}
    <section>
        <div class="title">
            <img src="{% static 'web/img/premium-icon.svg' %}" alt="" class="mr-10">
            {% trans 'Premium ads' %}
        </div>
        {% include 'partials/products_section.html' with type='pre' div_id='section_3' shuffled=True %}
        <div class="more">
            <p class='scrolltothis'></p>
        </div>    
    </section>
</main>
{% endblock %}

bolbol/web/templates/partials/replace.html
<script>
    window.jQuery ||
      document.write(
        '<script src="{% static 'web/libs/jquery/jquery-3.5.1.min.js' %}"><\/script>'
      );
  </script>

  <script
    src="{% static 'web/libs/popper.js' %}/popper.min.js' %}"
    type="text/javascript"
  ></script>

  <script
    src="{% static 'web/libs/bootstrap/bootstrap.min.js' %}"
    type="text/javascript"
    charset="utf-8"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sorttable/sorttable.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/lightslider/lightslider.js' %}"
  ></script>

  <script type="text/javascript" src="{% static 'web/libs/zoom/zoom.js' %}"></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sumogallery/jquery.sumogallery.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-select/bootstrap-select.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/moment.js' %}/moment.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-datetimepicker/tempusdominus-bootstrap-4.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/jquery-ui/jquery-ui.min.js' %}"
  ></script>

  <script src="{% static 'web/js/all.js' %}" type="text/javascript"></script>

  <script src="{% static 'web/js/newjs.js' %}"></script>
  <script src="{% static 'web/js/descFilters.js' %}"></script>

  <script type="text/javascript" src="{% static 'web/libs/typed.js' %}/typed.js' %}"></script>
  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. 
      <script>
          window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
          ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
      </script>-->
  <!-- <script
    src="https://www.google-analytics.com/analytics.js' %}"
    async
    defer
  ></script> -->

  <script>
    window.jQuery ||
      document.write(
        '<script src="{% static 'web/libs/jquery/jquery-3.5.1.min.js' %}"><\/script>'
      );
  </script>
  <script src="{% static 'web/js/filterTarix.js' %}"></script>
  <script
    src="{% static 'web/libs/popper.js' %}/popper.min.js' %}"
    type="text/javascript"
  ></script>

  <script
    src="{% static 'web/libs/bootstrap/bootstrap.min.js' %}"
    type="text/javascript"
    charset="utf-8"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sorttable/sorttable.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/lightslider/lightslider.js' %}"
  ></script>

  <script type="text/javascript" src="{% static 'web/libs/zoom/zoom.js' %}"></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sumogallery/jquery.sumogallery.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-select/bootstrap-select.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/moment.js' %}/moment.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-datetimepicker/tempusdominus-bootstrap-4.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/jquery-ui/jquery-ui.min.js' %}"
  ></script>

  <script src="{% static 'web/js/all.js' %}" type="text/javascript"></script>

  <!-- <script src="{% static 'web/js/newjs.js' %}"></script> -->
  <script src="{% static 'web/js/descFilters.js' %}"></script>

  <script type="text/javascript" src="{% static 'web/libs/typed.js' %}/typed.js' %}"></script>
</body>
</html>

bolbol/web/templates/partials/scripts.html
{% load static %}
<script>
    window.jQuery ||
      document.write(
        `<script src="{% static 'web/libs/jquery/jquery-3.5.1.min.js' %}"><\/script>`
      );
  </script>

  <script
    src="{% static 'web/libs/popper.js' %}"
    type="text/javascript"
  ></script>

  <script
    src="{% static 'web/libs/bootstrap/bootstrap.min.js' %}"
    type="text/javascript"
    charset="utf-8"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sorttable/sorttable.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/lightslider/lightslider.js' %}"
  ></script>

  <script type="text/javascript" src="{% static 'web/libs/zoom/zoom.js' %}"></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/sumogallery/jquery.sumogallery.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/typed.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/inputmask/jquery.inputmask.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-select/bootstrap-select.min.js' %}"
  ></script>
<!-- 
  <script
    type="text/javascript"
    src="{% static 'web/libs/moment.js/moment.js' %}"
  ></script> -->
  <script
    type="text/javascript"
    src="{% static 'web/libs/moment.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/bootstrap-datetimepicker/tempusdominus-bootstrap-4.min.js' %}"
  ></script>

  <script
    type="text/javascript"
    src="{% static 'web/libs/jquery-ui/jquery-ui.min.js' %}"
  ></script>

  
  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. 
    <script>
      window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
      ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
    </script>-->
    <script
    src="https://www.google-analytics.com/analytics.js' %}"
    async
    defer
    ></script>

    <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
    <script type="text/javascript" src="{% static 'web/js/_typed.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/all.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/code.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/code4.js' %}"></script>

  <!-- Load library from the CDN -->

  <!-- Setup and start animation! -->

bolbol/web/templates/web/test.html
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var carousel = new Flickity(".carousel", {
      prevNextButtons: false, // Отключаем кнопки навигации
      pageDots: false, // Отключаем точки навигации
      contain: true, // Принудительно ограничиваем ширину контейнера
      draggable: true, // Запрещаем перетаскивание для скроллинга
      cellAlign: "left", // Выравниваем элементы к левому краю
    });
    
    // Автоматический скролл к последнему элементу
    carousel.select(0);
  });
</script>

<script src="assets/js/all.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flickity/2.2.2/flickity.pkgd.min.js"></script>
<script src="{% static 'web/js/emlak.js' %}"></script>
<!-- <script src="assets/js/descFilters.js"></script> -->

<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. 
   <script>
       window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
       ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
   </script>-->
<script
  src="https://www.google-analytics.com/analytics.js"
  async
  defer
></script>
<script type="text/javascript" src="{% static 'web/js/descFilters.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/filter.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/emlak.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/emlakSeher.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/filterTarix.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/kategory.js' %}"></script>
<script type="text/javascript" src="{% static 'web/js/newjs.js' %}"></script>